name: stHorses
version: 1.0.1
description: Store horses in a saddle
author: Jerred Shepherd (RiotShielder)
website: http://shepherdjerred.com/

main: com.shepherdjerred.sthorses.Main

commands:
    sth:
        description: Base command
        aliases: [sthorses]
        
permissions:
    stHorses.*:
        description: Gives access to all plugin functions
        children:
            stHorses.reload: true
            stHorses.save: true
            stHorses.spawn: true
    stHorses.reload:
        description: Gives access to /sth reload
        default: op
    stHorses.save:
        description: Allows saving horses to saddles
        default: true
    stHorses.spawn:
        description: Allows spawning horses from saddles
        default: true